#!/bin/bash

echo 'db2inst1:cl@v301' | chpasswd

su - db2inst1 <<'EOF'
  db2start
  db2sampl
  db2 connect to sample

  # db2 "drop INDEX SPCI371"
  # db2 "drop INDEX SPCI371"
  # db2 "drop INDEX SPCI373"
  # db2 "drop INDEX SPCI370"

  db2 "drop table SPCT37_DIRECCIONES"
  db2 """CREATE TABLE SPCT37_DIRECCIONES
            (NUMPERSO DECIMAL(13 , 0) NOT NULL, EMPRESA DECIMAL(5 , 0) NOT NULL,
             TIPDIR CHAR(1) FOR MIXED DATA NOT NULL, PRIORIDA DECIMAL(3 , 0) NOT NULL,
             DIRECCIO CHAR(60) FOR MIXED DATA NOT NULL, CPOSTAL CHAR(5) FOR MIXED DATA NOT NULL,
             LOCALIDA CHAR(45) FOR MIXED DATA NOT NULL, PROVIN CHAR(2) FOR MIXED DATA NOT NULL,
             PAIS CHAR(3) FOR MIXED DATA NOT NULL, LOCINOM DECIMAL(3 , 0) NOT NULL,
             LOCINUM DECIMAL(3 , 0) NOT NULL, INNORMAL CHAR(1) FOR MIXED DATA NOT NULL,
             CDRTAPOB DECIMAL(11 , 0) NOT NULL, CDRTAVIA DECIMAL(11 , 0) NOT NULL,
             CDRTAZON DECIMAL(11 , 0) NOT NULL, FECALTA DATE NOT NULL WITH DEFAULT,
             FEINIAPL DECIMAL(7 , 0) NOT NULL, FEFINAPL DECIMAL(7 , 0) NOT NULL,
             FECULTIM DATE NOT NULL WITH DEFAULT, HORULTIM DECIMAL(7 , 0) NOT NULL,
             USUMODI CHAR(8) FOR MIXED DATA NOT NULL, CANMODI DECIMAL(9 , 0) NOT NULL,
             FECNORMA DECIMAL(7 , 0) NOT NULL WITH DEFAULT, HOGARID DECIMAL(11 , 0) NOT NULL WITH DEFAULT,
             FEALHOID DECIMAL(7 , 0) NOT NULL WITH DEFAULT, FEULMIDH DECIMAL(7 , 0) NOT NULL WITH DEFAULT,
             INDDESGL CHAR(1) FOR MIXED DATA NOT NULL WITH DEFAULT,
             TIPOVIA CHAR(3) FOR MIXED DATA NOT NULL WITH DEFAULT,
             NOMCARRE CHAR(60) FOR MIXED DATA NOT NULL WITH DEFAULT, NUMDESDE DECIMAL(5 , 0) NOT NULL WITH DEFAULT,
             NUMHASTA CHAR(10) FOR MIXED DATA NOT NULL WITH DEFAULT,
             NUMEDIFI CHAR(25) FOR MIXED DATA NOT NULL WITH DEFAULT, NUMESCAL CHAR(5) FOR MIXED DATA NOT NULL WITH DEFAULT,
             NUMERPIS CHAR(15) FOR MIXED DATA NOT NULL WITH DEFAULT, NUMEPORT CHAR(5) FOR MIXED DATA NOT NULL WITH DEFAULT,
             RESTA CHAR(40) FOR MIXED DATA NOT NULL WITH DEFAULT, INDBLOC DECIMAL(1 , 0) NOT NULL WITH DEFAULT,
             INIVALID DATE NOT NULL WITH DEFAULT, FINVALID DATE NOT NULL,
             ROWBEGIN TIMESTAMP(12) NOT NULL NOT NULL GENERATED ALWAYS AS ROW BEGIN,
             ROWEND TIMESTAMP(12) NOT NULL GENERATED ALWAYS AS ROW END,
             CHGTMST TIMESTAMP(6) NOT NULL GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP  IMPLICITLY HIDDEN,
             ID_COL INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (NO MINVALUE NO MAXVALUE NO CYCLE CACHE 20 NO ORDER),
             PERIOD BUSINESS_TIME(INIVALID, FINVALID), PERIOD SYSTEM_TIME(ROWBEGIN, ROWEND) )

             """
EOF

su - db2inst1 <<'EOF'
  db2 connect to sample
  for i in {1..100}
  do
      db2 """insert into SPCT37_DIRECCIONES(NUMPERSO, EMPRESA, TIPDIR, PRIORIDA, DIRECCIO, CPOSTAL, LOCALIDA, PROVIN,
             PAIS, LOCINOM, LOCINUM, INNORMAL, CDRTAPOB, CDRTAVIA, CDRTAZON, FECALTA, FEINIAPL, FEFINAPL,
             FECULTIM, HORULTIM, USUMODI, CANMODI, FECNORMA, HOGARID, FEALHOID, FEULMIDH, INDDESGL,
             TIPOVIA, NOMCARRE, NUMDESDE, NUMHASTA, NUMEDIFI, NUMESCAL, NUMERPIS, NUMEPORT, RESTA, INDBLOC, INIVALID, FINVALID)
             values
             (1.0, 5.0, 'a', 3.0, 'direccion', 46010, 'LOCALIDA', 'CS', 'ESP', 3.0,
              4.0, 'A', 11.0, 11.0, 11.0, DATE ('2002-10-20'), 7.0, 7.0, DATE ('2002-10-21'), 7.0, 'USUMODI', 9.0,
              7.0, 11.0, 7.0, 7.0, 'M', 'TIV', 'NOMCARRE', 5.0, 'NUMHASTA', 'NUMEDIFICI', 'NUMES', 'NUMERPIS', 'NUMEP',
              'RESTA', 1.0, DATE ('2002-10-22'), DATE ('2002-10-23'))
          """
  done
  # Comentados para evitar error de inserción por clave única, ya que nuestros datos no son muy elaborados
  # db2 "CREATE INDEX SPCI371 ON SPCT37_DIRECCIONES (INIVALID DESC, FINVALID, FECALTA)"
  # db2 "CREATE INDEX SPCI373 ON SPCT37_DIRECCIONES (CHGTMST, ID_COL)"
  # db2 "CREATE UNIQUE INDEX SPCI370 ON SPCT37_DIRECCIONES (EMPRESA ASC, NUMPERSO ASC, BUSINESS_TIME WITHOUT OVERLAPS)"
  # db2 "ALTER TABLE SPCT37_DIRECCIONES ADD CONSTRAINT EMPRESA PRIMARY KEY (EMPRESA, NUMPERSO, BUSINESS_TIME WITHOUT OVERLAPS)"
  db2 """
    CREATE PROCEDURE SPCXKAF (IN TSTAMPI TIMESTAMP,
                              IN TSTAMPF TIMESTAMP,
                              IN IDCOL   INTEGER )
    P1: BEGIN
              DECLARE cursor1 CURSOR WITH RETURN FOR
           SELECT NUMPERSO, LOCALIDA, DIRECCIO,
                  ID_COL, CHGTMST
           FROM SPCT37_DIRECCIONES
           WHERE CHGTMST < TSTAMPF AND
                ((CHGTMST = TSTAMPI AND ID_COL > IDCOL) OR CHGTMST > TSTAMPI)
           ORDER BY CHGTMST,ID_COL ASC
           FETCH FIRST 50 ROWS ONLY
           OPTIMIZE FOR 50 ROWS;
              OPEN cursor1;
    END P1
  """
EOF


su - db2inst1 <<'EOF'
  db2 connect to sample
  db2 "select * from SPCT37_DIRECCIONES"
EOF
