CREATE  TABLESPACE "SPCE37G"
	IN SPCB011
	USING STOGROUP G97121
	  PRIQTY -1
	  SECQTY -1
	DSSIZE 4 G
	MAXPARTITIONS 4
	SEGSIZE 32
	BUFFERPOOL BP0
	CCSID UNICODE
	COMPRESS YES
	LOCKMAX SYSTEM
	LOCKSIZE ANY
	MAXROWS 255;
  COMMIT;
  
CREATE TABLE "PB97121"."SPCT37_DIRECCIONES" (
		"NUMPERSO" DECIMAL(13 , 0) NOT NULL, 
		"EMPRESA" DECIMAL(5 , 0) NOT NULL, 
		"TIPDIR" CHAR(1) FOR MIXED DATA NOT NULL, 
		"PRIORIDA" DECIMAL(3 , 0) NOT NULL, 
		"DIRECCIO" CHAR(60) FOR MIXED DATA NOT NULL, 
		"CPOSTAL" CHAR(5) FOR MIXED DATA NOT NULL, 
		"LOCALIDA" CHAR(45) FOR MIXED DATA NOT NULL, 
		"PROVIN" CHAR(2) FOR MIXED DATA NOT NULL, 
		"PAIS" CHAR(3) FOR MIXED DATA NOT NULL, 
		"LOCINOM" DECIMAL(3 , 0) NOT NULL, 
		"LOCINUM" DECIMAL(3 , 0) NOT NULL, 
		"INNORMAL" CHAR(1) FOR MIXED DATA NOT NULL, 
		"CDRTAPOB" DECIMAL(11 , 0) NOT NULL, 
		"CDRTAVIA" DECIMAL(11 , 0) NOT NULL, 
		"CDRTAZON" DECIMAL(11 , 0) NOT NULL, 
		"FECALTA" DATE NOT NULL WITH DEFAULT, 
		"FEINIAPL" DECIMAL(7 , 0) NOT NULL, 
		"FEFINAPL" DECIMAL(7 , 0) NOT NULL, 
		"FECULTIM" DATE NOT NULL WITH DEFAULT, 
		"HORULTIM" DECIMAL(7 , 0) NOT NULL, 
		"USUMODI" CHAR(8) FOR MIXED DATA NOT NULL, 
		"CANMODI" DECIMAL(9 , 0) NOT NULL, 
		"FECNORMA" DECIMAL(7 , 0) NOT NULL WITH DEFAULT, 
		"HOGARID" DECIMAL(11 , 0) NOT NULL WITH DEFAULT, 
		"FEALHOID" DECIMAL(7 , 0) NOT NULL WITH DEFAULT, 
		"FEULMIDH" DECIMAL(7 , 0) NOT NULL WITH DEFAULT, 
		"INDDESGL" CHAR(1) FOR MIXED DATA NOT NULL WITH DEFAULT, 
		"TIPOVIA" CHAR(3) FOR MIXED DATA NOT NULL WITH DEFAULT, 
		"NOMCARRE" CHAR(60) FOR MIXED DATA NOT NULL WITH DEFAULT, 
		"NUMDESDE" DECIMAL(5 , 0) NOT NULL WITH DEFAULT, 
		"NUMHASTA" CHAR(10) FOR MIXED DATA NOT NULL WITH DEFAULT, 
		"NUMEDIFI" CHAR(25) FOR MIXED DATA NOT NULL WITH DEFAULT, 
		"NUMESCAL" CHAR(5) FOR MIXED DATA NOT NULL WITH DEFAULT, 
		"NUMERPIS" CHAR(15) FOR MIXED DATA NOT NULL WITH DEFAULT, 
		"NUMEPORT" CHAR(5) FOR MIXED DATA NOT NULL WITH DEFAULT, 
		"RESTA" CHAR(40) FOR MIXED DATA NOT NULL WITH DEFAULT, 
		"INDBLOC" DECIMAL(1 , 0) NOT NULL WITH DEFAULT, 
		"INIVALID" DATE NOT NULL WITH DEFAULT, 
		"FINVALID" DATE NOT NULL, 
		"ROWBEGIN" TIMESTAMP NOT NULL GENERATED ALWAYS AS ROW BEGIN , 
		"ROWEND" TIMESTAMP NOT NULL GENERATED ALWAYS AS ROW END , 
		"CHGTMST" TIMESTAMP NOT NULL GENERATED ALWAYS FOR EACH ROW ON UPDATE AS ROW CHANGE TIMESTAMP  IMPLICITLY HIDDEN , 
		"ID_COL" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (
			NO MINVALUE 
			NO MAXVALUE 
			NO CYCLE
			CACHE 20
			NO ORDER ), 
		PERIOD BUSINESS_TIME("INIVALID", "FINVALID"), 
		PERIOD SYSTEM_TIME("ROWBEGIN", "ROWEND")
	)
	IN "SPCB011"."SPCE37G"
	PARTITION BY SIZE EVERY 4 G 
	AUDIT NONE
	DATA CAPTURE NONE 
	CCSID UNICODE;

CREATE INDEX "PB97121"."SPCI371"
	ON "PB97121"."SPCT37_DIRECCIONES"
	("INIVALID"		DESC, 
	  "FINVALID"		DESC, 
	  "FECALTA"		DESC)
	NOT CLUSTER
	USING STOGROUP G97121
	  PRIQTY 716
	  SECQTY 716
	BUFFERPOOL BP1     
	CLOSE NO
	PIECESIZE 4194304 K;

CREATE INDEX "PB97121"."SPCI373"
	ON "PB97121"."SPCT37_DIRECCIONES"
	("CHGTMST"		ASC, 
	  "ID_COL"		ASC)
	NOT CLUSTER
	USING STOGROUP G97121
	  PRIQTY 716
	  SECQTY 716
	BUFFERPOOL BP1     
	CLOSE NO
	PIECESIZE 4194304 K;

CREATE UNIQUE INDEX "PB97121"."SPCI370"
	ON "PB97121"."SPCT37_DIRECCIONES"
	("EMPRESA"		ASC, 
	  "NUMPERSO"		ASC,  BUSINESS_TIME WITHOUT OVERLAPS)
	CLUSTER
	USING STOGROUP G97121
	  PRIQTY 716
	  SECQTY 716
	BUFFERPOOL BP1     
	CLOSE NO
	PIECESIZE 4194304 K;

ALTER TABLE "PB97121"."SPCT37_DIRECCIONES" ADD CONSTRAINT "EMPRESA" PRIMARY KEY
	("EMPRESA", 
	 "NUMPERSO",  BUSINESS_TIME WITHOUT OVERLAPS);

GRANT ALTER ON TABLE "PB97121"."SPCT37_DIRECCIONES" TO "PB97121" WITH GRANT OPTION;

GRANT DELETE ON TABLE "PB97121"."SPCT37_DIRECCIONES" TO "PB97121" WITH GRANT OPTION;

GRANT INDEX ON TABLE "PB97121"."SPCT37_DIRECCIONES" TO "PB97121" WITH GRANT OPTION;

GRANT INSERT ON TABLE "PB97121"."SPCT37_DIRECCIONES" TO "PB97121" WITH GRANT OPTION;

GRANT REFERENCES ON TABLE "PB97121"."SPCT37_DIRECCIONES" TO "PB97121" WITH GRANT OPTION;

GRANT SELECT ON TABLE "PB97121"."SPCT37_DIRECCIONES" TO "PB97121" WITH GRANT OPTION;

GRANT TRIGGER ON TABLE "PB97121"."SPCT37_DIRECCIONES" TO "PB97121" WITH GRANT OPTION;

GRANT UPDATE ON TABLE "PB97121"."SPCT37_DIRECCIONES" TO "PB97121" WITH GRANT OPTION;
