#!/bin/sh
echo Cargamos las variables de entorno ...
eval $(docker-machine.exe env DCAYDCB)
echo Paramos los contenedores ...
docker-compose -f docker-compose-4.yml stop
echo Paramos la máquina virtual ...
docker-machine stop DCAYDCB
